### ISSUE TITLE
Refactor Event Logging to Provide Detailed Object Information

### ISSUE THREAD

**Issue by Rahul-D78** [kubeslice/kubeslice-monitoring#39]
### Current Behavior

Currently, Kubernetes events are logged using a generic format that includes the entire object.

```GO
er.Logger.Infof("event has been created %v", ev)
er.Logger.Debugf("event has been updated %v", ev)
```

### Desired Behavior
Refactoring of the event logging mechanism to provide more detailed information about the involved object, including namespace, name, kind, event type, reason, and message.

### Reason for Change
The current logging format making it difficult to quickly understand the context and severity of events. By adopting a more structured and informative logging format, we can improve readability, simplify troubleshooting, and enhance our overall monitoring capabilities.

### Proposed Solution
Refactor the event logging code to log events in the following format:
```GO
er.Logger.Infof("event has been created object: %s/%s kind: %s type: %s reason %s message %s",
	ev.InvolvedObject.Namespace, ev.InvolvedObject.Name, ev.InvolvedObject.Kind, ev.Type, ev.Reason, ev.Message)
```

### Sample Example:
```shell
{"severity":"info","time":"2024-04-15T01:30:49Z","message":"event has been created object: kubeslice-avesha/cluster1 kind: Cluster type: Normal reason ClusterCNISubnetUpdateSuccessful message cluster CNI Subnet updated successfully.","namespace":"kubeslice-system","sliceCluster":"cluster1","name":"worker-operator"}

```

**Comment by Geun-Oh** [comment]
Hello. can I work on this issue? kindly assign it to me.

**Comment by narmidm** [comment]
sure @Geun-Oh. I have assigned this issue to you. Let us know @Geun-Oh if you need any help with this issue.
